config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def name
    "Bianca"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # list all blogs
  def index
    @blogs = Blog.all.order(:id)
  end

  # display blog based on id
  def show
    @blog = Blog.find(params[:id])
  end

  # create new blog instance
  def new
    @blog = Blog.new
  end

  # edit blog
  def edit
    @blog = Blog.find(params[:id])
  end

  # add blog to database
  def create
    @blog = Blog.new(params.require(:blog).permit(:title, :text, :body, :text))

    if @blog.save
      redirect_to @blog, alert: "Blog created successfully"
    else
      redirect_to new_blog_path, alert: "Error creating blog"
    end
  end

  # edit existing blog in database
  def update
    @blog = Blog.find(params[:id])

    if @blog.update(params.require(:blog).permit(:title, :text, :body, :text))
      redirect_to @blog
    else
      render "Edit"
    end
  end

  # delete blog from database
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to blogs_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form|%>
  <p>
    <%= form.label :title %><br/>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :body %><br/>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit :save %>
  </p>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render "form" %>

<%= link_to "Back", blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.body %></td>
      <td><%= link_to "View", blog_path(blog) %></td>
      <td><%= link_to "Edit", edit_blog_path(blog) %></td>
      <td><%= link_to "Delete", blog_path(blog), method: :delete, data: { confirm: "Are you sure you want to delete this blog from the database?" } %></td>

    </tr>
  <% end%>
</table>
<br/>
<%= link_to "New Blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render "form" %>

<%= link_to "Back", blogs_path %>

app/views/blogs/show.html.erb
<p>
<strong>Title:</strong>
<%= @blog.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @blog.body %>
</p>

<%= link_to "Back", blogs_path %>
<%= link_to "Edit", edit_blog_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>